language: dart

dart:
  - "2.8.4" # Change back to stable if we find a path forward with https://github.com/dart-lang/sdk/issues/42977

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

script:
- pub run dart_dev format --check
- dartanalyzer .
- pub run dependency_validator -i dart_style,over_react,pedantic
- pub run test

