targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - '**.sg.dart'
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
