name: over_react_codemod
version: 1.1.0
homepage: https://github.com/Workiva/over_react_codemod

description: >
  Codemods for consumers of over_react that automate the migration of
  UI component code.

authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Corwin Sheahan <corwin.sheahan@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - George Lesica <george.lesica@workiva.com>
  - Sebastian Malysa <sebastian.malysa@workiva.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  analyzer: '>=0.37.0 <0.39.0'
  args: ^1.5.1
  codemod: ^0.1.5
  meta: ^1.1.6
  path: ^1.6.2
  pub_semver: ^1.4.2
  source_span: ^1.4.1

dev_dependencies:
  dart_dev: ^2.0.1
  dart_style: ^1.2.0
  dependency_validator: ^1.2.3
  mockito: ^4.0.0
  pedantic: ^1.4.0
  react: ^4.6.1
  test: ^1.5.1

executables:
  dart2_upgrade:
  component2_upgrade:
