name: codemod_over_react
private: true
version: 0.0.0

dependencies:
  analyzer: ^0.33.6+1
  codemod:
    git:
      url: git@github.com:Workiva/dart_codemod.git
      ref: 5cfda9d2438e4a4ce9d8938315ef0cebf727365f # initial
  path: ^1.6.2
  source_span: ^1.4.1

dev_dependencies:
  dart_dev: ^2.0.1
  dart_style: ^1.2.0
  dependency_validator: ^1.2.3
  mockito: ^4.0.0
  test: ^1.5.1

executables:
  migrate_from_dart1_to_dart1_and_dart2: